<?php

/**
 * This is the model base class for the table "gpdocument".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gpdocument".
 *
 * Columns in table "gpdocument" available as properties of the model,
 * followed by relations of table "gpdocument" available as properties of the model.
 *
 * @property string $id
 * @property string $gp_id
 * @property string $file
 *
 * @property Gp $gp
 */
abstract class BaseGpdocument extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gpdocument';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gpdocument|Gpdocuments', $n);
	}

	public static function representingColumn() {
		return 'file';
	}

	public function rules() {
		return array(
			array('gp_id, file', 'required'),
			array('gp_id', 'length', 'max'=>10),
			array('file', 'length', 'max'=>30),
			array('id, gp_id, file', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gp' => array(self::BELONGS_TO, 'Gp', 'gp_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'gp_id' => null,
			'file' => Yii::t('app', 'File'),
			'gp' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('gp_id', $this->gp_id);
		$criteria->compare('file', $this->file, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}