<?php

/**
 * This is the model base class for the table "sector".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sector".
 *
 * Columns in table "sector" available as properties of the model,
 * followed by relations of table "sector" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 *
 * @property Employeessector[] $employeessectors
 */
abstract class BaseSector extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sector';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sector|Sectors', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>50),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeessectors' => array(self::HAS_MANY, 'Employeessector', 'sector_id'),
            'lpsectors' => array(self::HAS_MANY, 'Lpsector', 'sector_id'),
            'Lps' => array(self::HAS_MANY, 'Lp', 'lpsector(sector_id, lp_id)'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'employeessectors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
