<?php

/**
 * This is the model base class for the table "lpsegment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lpsegment".
 *
 * Columns in table "lpsegment" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $segment_id
 * @property integer $lp_id
 *
 */
abstract class BaseLpsegment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lpsegment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lpsegment|Lpsegments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('segment_id, lp_id', 'numerical', 'integerOnly'=>true),
			array('segment_id, lp_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, segment_id, lp_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'segment_id' => Yii::t('app', 'Segment'),
			'lp_id' => Yii::t('app', 'Lp'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('segment_id', $this->segment_id);
		$criteria->compare('lp_id', $this->lp_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}