<?php

/**
 * This is the model base class for the table "lpdocument".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lpdocument".
 *
 * Columns in table "lpdocument" available as properties of the model,
 * followed by relations of table "lpdocument" available as properties of the model.
 *
 * @property string $id
 * @property string $lp_id
 * @property string $file
 *
 * @property Lp $lp
 */
abstract class BaseLpdocument extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lpdocument';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lpdocument|Lpdocuments', $n);
	}

	public static function representingColumn() {
		return 'file';
	}

	public function rules() {
		return array(
			array('lp_id, file', 'required'),
			array('lp_id', 'length', 'max'=>10),
			array('file', 'length', 'max'=>30),
			array('id, lp_id, file', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'lp' => array(self::BELONGS_TO, 'Lp', 'lp_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'lp_id' => null,
			'file' => Yii::t('app', 'File'),
			'lp' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('lp_id', $this->lp_id);
		$criteria->compare('file', $this->file, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}