<?php

/**
 * This is the model base class for the table "communication".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Communication".
 *
 * Columns in table "communication" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $gp_id
 * @property integer $client_mandate_id
 * @property integer $user_id
 * @property integer $employees_id
 *
 */
abstract class BaseCommunication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'communication';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Communication|Communications', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('gp_id, client_mandate_id, user_id, employees_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description, gp_id, client_mandate_id, user_id, employees_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, gp_id, client_mandate_id, user_id, employees_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'gp_id' => Yii::t('app', 'Gp'),
			'client_mandate_id' => Yii::t('app', 'Client Mandate'),
			'user_id' => Yii::t('app', 'User'),
			'employees_id' => Yii::t('app', 'Employees'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('gp_id', $this->gp_id);
		$criteria->compare('client_mandate_id', $this->client_mandate_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('employees_id', $this->employees_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}