<?php

/**
 * This is the model base class for the table "gpsector".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gpsector".
 *
 * Columns in table "gpsector" available as properties of the model,
 * followed by relations of table "gpsector" available as properties of the model.
 *
 * @property string $id
 * @property string $gp_id
 * @property string $sector_id
 *
 * @property Gp $gp
 * @property Sector $sector
 */
abstract class BaseGpsector extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gpsector';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gpsector|Gpsectors', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('gp_id, sector_id', 'required'),
			array('gp_id, sector_id', 'length', 'max'=>10),
			array('id, gp_id, sector_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gp' => array(self::BELONGS_TO, 'Gp', 'gp_id'),
			'sector' => array(self::BELONGS_TO, 'Sector', 'sector_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'gp_id' => null,
			'sector_id' => null,
			'gp' => null,
			'sector' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('gp_id', $this->gp_id);
		$criteria->compare('sector_id', $this->sector_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}