<?php

/**
 * This is the model base class for the table "lpregion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lpregion".
 *
 * Columns in table "lpregion" available as properties of the model,
 * followed by relations of table "lpregion" available as properties of the model.
 *
 * @property string $id
 * @property string $lp_id
 * @property string $region_id
 *
 * @property Lp $lp
 * @property Region $region
 */
abstract class BaseLpregion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lpregion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lpregion|Lpregions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('lp_id, region_id', 'required'),
			array('lp_id, region_id', 'length', 'max'=>10),
			array('id, lp_id, region_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'lp' => array(self::BELONGS_TO, 'Lp', 'lp_id'),
			'region' => array(self::BELONGS_TO, 'Region', 'region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'lp_id' => null,
			'region_id' => null,
			'lp' => null,
			'region' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('lp_id', $this->lp_id);
		$criteria->compare('region_id', $this->region_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}