<?php

/**
 * This is the model base class for the table "officecontinent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Officecontinent".
 *
 * Columns in table "officecontinent" available as properties of the model,
 * followed by relations of table "officecontinent" available as properties of the model.
 *
 * @property string $id
 * @property string $office_id
 * @property string $continent_id
 *
 * @property Continent $continent
 * @property Office $office
 */
abstract class BaseOfficecontinent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'officecontinent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Officecontinent|Officecontinents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('office_id, continent_id', 'required'),
			array('office_id, continent_id', 'length', 'max'=>10),
			array('id, office_id, continent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'continent' => array(self::BELONGS_TO, 'Continent', 'continent_id'),
			'office' => array(self::BELONGS_TO, 'Office', 'office_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'office_id' => null,
			'continent_id' => null,
			'continent' => null,
			'office' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('office_id', $this->office_id);
		$criteria->compare('continent_id', $this->continent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}