<?php

/**
 * This is the model base class for the table "lpfundsize".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lpfundsize".
 *
 * Columns in table "lpfundsize" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $lp_id
 * @property integer $fundsize_id
 *
 */
abstract class BaseLpfundsize extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lpfundsize';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lpfundsize|Lpfundsizes', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('lp_id, fundsize_id', 'numerical', 'integerOnly'=>true),
			array('lp_id, fundsize_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, lp_id, fundsize_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'lp_id' => Yii::t('app', 'Lp'),
			'fundsize_id' => Yii::t('app', 'Fundsize'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('lp_id', $this->lp_id);
		$criteria->compare('fundsize_id', $this->fundsize_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}