<?php

/**
 * This is the model base class for the table "employeesregion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Employeesregion".
 *
 * Columns in table "employeesregion" available as properties of the model,
 * followed by relations of table "employeesregion" available as properties of the model.
 *
 * @property string $id
 * @property string $employees_id
 * @property string $region_id
 *
 * @property Region $region
 * @property Employees $employees
 */
abstract class BaseEmployeesregion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'employeesregion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Employeesregion|Employeesregions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('employees_id, region_id', 'required'),
			array('employees_id, region_id', 'length', 'max'=>10),
			array('id, employees_id, region_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'region' => array(self::BELONGS_TO, 'Region', 'region_id'),
			'employees' => array(self::BELONGS_TO, 'Employees', 'employees_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'employees_id' => null,
			'region_id' => null,
			'region' => null,
			'employees' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('employees_id', $this->employees_id);
		$criteria->compare('region_id', $this->region_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}