<?php

/**
 * This is the model base class for the table "gp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gp".
 *
 * Columns in table "gp" available as properties of the model,
 * followed by relations of table "gp" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $website
 * @property string $rank
 * @property string $firm_id
 *
 * @property Firm $firm
 * @property Gpcontinent[] $gpcontinents
 * @property Gpdocument[] $gpdocuments
 * @property Gpregion[] $gpregions
 * @property Gpsector[] $gpsectors
 */
abstract class BaseGp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gp';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gp|Gps', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('rank, firm_id', 'required'),
			array('name', 'length', 'max'=>50),
			array('website', 'length', 'max'=>100),
			array('rank', 'length', 'max'=>1),
			array('firm_id', 'length', 'max'=>10),
			array('description', 'safe'),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, website, rank, firm_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'firm' => array(self::BELONGS_TO, 'Firm', 'firm_id'),
			'gpcontinents' => array(self::HAS_MANY, 'Gpcontinent', 'gp_id'),
			'gpdocuments' => array(self::HAS_MANY, 'Gpdocument', 'gp_id'),
			'gpregions' => array(self::HAS_MANY, 'Gpregion', 'gp_id'),
			'gpsectors' => array(self::HAS_MANY, 'Gpsector', 'gp_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'website' => Yii::t('app', 'Website'),
			'rank' => Yii::t('app', 'Rank'),
			'firm_id' => null,
			'firm' => null,
			'gpcontinents' => null,
			'gpdocuments' => null,
			'gpregions' => null,
			'gpsectors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('website', $this->website, true);
		$criteria->compare('rank', $this->rank, true);
		$criteria->compare('firm_id', $this->firm_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}