<?php

/**
 * This is the model base class for the table "client_mandate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClientMandate".
 *
 * Columns in table "client_mandate" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $gp_id
 *
 */
abstract class BaseClientMandate extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'client_mandate';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClientMandate|ClientMandates', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('gp_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description, gp_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, gp_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            'gp' => array(self::BELONGS_TO, 'Gp', 'gp_id'),
            'client_mandate_lps' => array(self::HAS_MANY, 'ClientMandateLp', 'client_mandate_id'),
            'lps' => array(self::MANY_MANY, 'Lp', 'client_mandate_lp(client_mandate_id, lp_id)'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'gp_id' => Yii::t('app', 'Gp'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('gp_id', $this->gp_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
