<?php

/**
 * This is the model base class for the table "firmregion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Firmregion".
 *
 * Columns in table "firmregion" available as properties of the model,
 * followed by relations of table "firmregion" available as properties of the model.
 *
 * @property string $id
 * @property string $firm_id
 * @property string $region_id
 *
 * @property Region $region
 * @property Firm $firm
 */
abstract class BaseFirmregion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'firmregion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Firmregion|Firmregions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('firm_id, region_id', 'required'),
			array('firm_id, region_id', 'length', 'max'=>10),
			array('id, firm_id, region_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'region' => array(self::BELONGS_TO, 'Region', 'region_id'),
			'firm' => array(self::BELONGS_TO, 'Firm', 'firm_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firm_id' => null,
			'region_id' => null,
			'region' => null,
			'firm' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('firm_id', $this->firm_id);
		$criteria->compare('region_id', $this->region_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}