<?php

/**
 * This is the model base class for the table "gpregion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gpregion".
 *
 * Columns in table "gpregion" available as properties of the model,
 * followed by relations of table "gpregion" available as properties of the model.
 *
 * @property string $id
 * @property string $gp_id
 * @property string $region_id
 *
 * @property Gp $gp
 * @property Region $region
 */
abstract class BaseGpregion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gpregion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gpregion|Gpregions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('gp_id, region_id', 'required'),
			array('gp_id, region_id', 'length', 'max'=>10),
			array('id, gp_id, region_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gp' => array(self::BELONGS_TO, 'Gp', 'gp_id'),
			'region' => array(self::BELONGS_TO, 'Region', 'region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'gp_id' => null,
			'region_id' => null,
			'gp' => null,
			'region' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('gp_id', $this->gp_id);
		$criteria->compare('region_id', $this->region_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}