<?php

/**
 * This is the model base class for the table "employeescontinent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Employeescontinent".
 *
 * Columns in table "employeescontinent" available as properties of the model,
 * followed by relations of table "employeescontinent" available as properties of the model.
 *
 * @property string $id
 * @property string $employees_id
 * @property string $continent_id
 *
 * @property Continent $continent
 * @property Employees $employees
 */
abstract class BaseEmployeescontinent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'employeescontinent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Employeescontinent|Employeescontinents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('employees_id, continent_id', 'required'),
			array('employees_id, continent_id', 'length', 'max'=>10),
			array('id, employees_id, continent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'continent' => array(self::BELONGS_TO, 'Continent', 'continent_id'),
			'employees' => array(self::BELONGS_TO, 'Employees', 'employees_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'employees_id' => null,
			'continent_id' => null,
			'continent' => null,
			'employees' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('employees_id', $this->employees_id);
		$criteria->compare('continent_id', $this->continent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}