<?php

/**
 * This is the model base class for the table "region".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Region".
 *
 * Columns in table "region" available as properties of the model,
 * followed by relations of table "region" available as properties of the model.
 *
 * @property string $id
 * @property string $continent_id
 * @property string $name
 *
 * @property Employeesregion[] $employeesregions
 * @property Firmregion[] $firmregions
 * @property Gpregion[] $gpregions
 * @property Lpregion[] $lpregions
 * @property Officeregion[] $officeregions
 */
abstract class BaseRegion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'region';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Region|Regions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('continent_id, name', 'required'),
			array('continent_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>50),
			array('id, continent_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeesregions' => array(self::HAS_MANY, 'Employeesregion', 'region_id'),
			'firmregions' => array(self::HAS_MANY, 'Firmregion', 'region_id'),
			'gpregions' => array(self::HAS_MANY, 'Gpregion', 'region_id'),
			'lpregions' => array(self::HAS_MANY, 'Lpregion', 'region_id'),
			'officeregions' => array(self::HAS_MANY, 'Officeregion', 'region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'continent_id' => Yii::t('app', 'Continent'),
			'name' => Yii::t('app', 'Name'),
			'employeesregions' => null,
			'firmregions' => null,
			'gpregions' => null,
			'lpregions' => null,
			'officeregions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('continent_id', $this->continent_id, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}