<?php

/**
 * This is the model base class for the table "firmdocument".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Firmdocument".
 *
 * Columns in table "firmdocument" available as properties of the model,
 * followed by relations of table "firmdocument" available as properties of the model.
 *
 * @property string $id
 * @property string $firm_id
 * @property string $file
 *
 * @property Firm $firm
 */
abstract class BaseFirmdocument extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'firmdocument';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Firmdocument|Firmdocuments', $n);
	}

	public static function representingColumn() {
		return 'file';
	}

	public function rules() {
		return array(
			array('firm_id, file', 'required'),
			array('firm_id', 'length', 'max'=>10),
			array('file', 'length', 'max'=>30),
			array('id, firm_id, file', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'firm' => array(self::BELONGS_TO, 'Firm', 'firm_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firm_id' => null,
			'file' => Yii::t('app', 'File'),
			'firm' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('firm_id', $this->firm_id);
		$criteria->compare('file', $this->file, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}