<?php

/**
 * This is the model base class for the table "todo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Todo".
 *
 * Columns in table "todo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $description
 * @property integer $user_id
 * @property string $create_at
 * @property string $date
 * @property integer $communication_id
 * @property integer $done
 *
 */
abstract class BaseTodo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'todo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Todo|Todos', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('user_id, communication_id, done', 'numerical', 'integerOnly'=>true),
			array('description, create_at, date', 'safe'),
			array('description, user_id, create_at, date, communication_id, done', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, user_id, create_at, date, communication_id, done', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'user_id' => Yii::t('app', 'User'),
			'create_at' => Yii::t('app', 'Create At'),
			'date' => Yii::t('app', 'Date'),
			'communication_id' => Yii::t('app', 'Communication'),
			'done' => Yii::t('app', 'Done'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('communication_id', $this->communication_id);
		$criteria->compare('done', $this->done);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}