<?php

/**
 * This is the model base class for the table "Lpcontinent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lpcontinent".
 *
 * Columns in table "Lpcontinent" available as properties of the model,
 * followed by relations of table "Lpcontinent" available as properties of the model.
 *
 * @property string $id
 * @property string $lp_id
 * @property string $continent_id
 * @property integer $top
 *
 * @property Continent $continent
 * @property Lp $lp
 */
abstract class BaseLpcontinent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lpcontinent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lpcontinent|Lpcontinents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('lp_id, continent_id, top', 'required'),
			array('top', 'numerical', 'integerOnly'=>true),
			array('lp_id, continent_id', 'length', 'max'=>10),
			array('id, lp_id, continent_id, top', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'continent' => array(self::BELONGS_TO, 'Continent', 'continent_id'),
			'lp' => array(self::BELONGS_TO, 'Lp', 'lp_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'lp_id' => null,
			'continent_id' => null,
			'top' => Yii::t('app', 'Top'),
			'continent' => null,
			'lp' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('lp_id', $this->lp_id);
		$criteria->compare('continent_id', $this->continent_id);
		$criteria->compare('top', $this->top);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}